### ISSUE TITLE
Development Mode

### ISSUE THREAD

**Issue by zenith-777** [NicosKaralis/pushmeup#24]
Hi,

I'm using your gem now and experienced some trouble in sending push notification. The problem that it always return 'nil' every time I tried. 
Apparently, I'm using development certificate and the APNS.host should be 'gateway.sandbox.push.apple.com'. (See this https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ProvisioningDevelopment.html)

So, I just want to add suggestion maybe you can add information in the readme or description about APNS host for development mode (gateway.sandbox.push.apple.com) is not the same with production mode (gateway.push.apple.com). There is no big issue at all, it's just that I don't know where I can comment for other user having similar experience with me. Thanks :-)

**Comment by NicosKaralis** [comment]
Fixed in commit 6fbe89407baed2673f213c657b83b6dbac72df3d
