### ISSUE TITLE
multiple push notification iOS

### ISSUE THREAD

**Issue by nelsongc** [NicosKaralis/pushmeup#27]
/usr/local/lib/ruby/gems/2.1.0/gems/railties-4.0.0/lib/rails/commands/runner.rb:53:in `eval': Broken pipe (Errno::EPIPE)
    from /usr/local/lib/ruby/2.1.0/openssl/buffering.rb:326:in`do_write'
    from /usr/local/lib/ruby/2.1.0/openssl/buffering.rb:344:in `write'
    from /usr/local/lib/ruby/gems/2.1.0/gems/pushmeup-0.1.2/lib/pushmeup/apns/core.rb:26:in`block in send_notifications'
    from /usr/local/lib/ruby/gems/2.1.0/gems/pushmeup-0.1.2/lib/pushmeup/apns/core.rb:25:in `each'
    from /usr/local/lib/ruby/gems/2.1.0/gems/pushmeup-0.1.2/lib/pushmeup/apns/core.rb:25:in`send_notifications'

this is happen when I try to send multiple notifications in average 3.000 notifications or more

**Comment by MaicolBen** [comment]
@nelsongc How did you solve this?

**Comment by feliperbferraz** [comment]
Hi @nelsongc , @MaicolBen did you find any solution?

**Comment by MaicolBen** [comment]
@feliperbferraz Use `APNS.start_persistence` and `APNS.stop_persistence`, I finally dropped this because APN has some issues with large amount of push notifications at the same time, I moved to Pushwoosh.

**Comment by feliperbferraz** [comment]
@MaicolBen Thanks for your response! I've tried with APNS.start_persistence and APNS.stop_persistence, but I couldn't get it working. Yes, I have sometimes to send for a huge percentage of my user base. I don't know about Pushwoosh, but I'll take a look if it fits better!
