### ISSUE TITLE
Getting undefined method `close` in apns/core.rb:83

### ISSUE THREAD

**Issue by suspiration** [NicosKaralis/pushmeup#29]
Getting an error when trying to run "ruby pushAPNS.rb

```
/Users/me/.rvm/gems/ruby-1.9.3-p545@global/gems/pushmeup-0.2.0/lib/pushmeup/apns/core.rb:83:in `rescue in with_connection': undefined method `close' for nil:NilClass (NoMethodError)
    from /Users/me/.rvm/gems/ruby-1.9.3-p545@global/gems/pushmeup-0.2.0/lib/pushmeup/apns/core.rb:72:in `with_connection'
    from /Users/me/.rvm/gems/ruby-1.9.3-p545@global/gems/pushmeup-0.2.0/lib/pushmeup/apns/core.rb:42:in `block in send_notifications'
    from <internal:prelude>:10:in `synchronize'
    from /Users/me/.rvm/gems/ruby-1.9.3-p545@global/gems/pushmeup-0.2.0/lib/pushmeup/apns/core.rb:41:in `send_notifications'
    from /Users/me/.rvm/gems/ruby-1.9.3-p545@global/gems/pushmeup-0.2.0/lib/pushmeup/apns/core.rb:37:in `send_notification'
    from pushAPNS.rb:12:in `<main>'
```

me@MacBook-    Pro.local:~/Documents/mobile/plugins/com.phonegap.plugins.PushPlugin/Example/server$

**Comment by NicosKaralis** [comment]
how often this error happens?

**Comment by suspiration** [comment]
Every time I run.  I tried with ruby 1.9.3, 2.0.0 and 2.1.1, all have the
same issue.

On Fri, Apr 4, 2014 at 6:47 AM, Nicos Belo Karalis <notifications@github.com

**Comment by aahlad-allari** [comment]
I am also getting the same issue!!

**Comment by aahlad-allari** [comment]
It is the problem with .pem file.

**Comment by NicosKaralis** [comment]
@aahladatparadigm could you elaborate? i was trying to find why the `@ssl` was nil, but i didnt find anything. why do you say it is the .pem file?

**Comment by suspiration** [comment]
Thanks @aahladatparadigm.

It is indeed the .pem file.  Looks like when you export the .pem file from Keychain Access, you have to select both the push services certificate as well as the private key.

**Comment by aahlad-allari** [comment]
Yes, We need both services certificate and private key.

**Comment by NicosKaralis** [comment]
problem solved, closing issue

**Comment by alexkravets** [comment]
Is there a way to articulate this pem problem in exception? Otherwise it requires googling.

**Comment by ericraio** [comment]
+1 for better error output

**Comment by dilizarov** [comment]
+1 for better error output

**Comment by iujlaki** [comment]
+1 for better error output

**Comment by YaroslavMykhaylyk** [comment]
+1 for better error output

**Comment by julio-castillo** [comment]
+1 for better error output
