### ISSUE TITLE
Notification to multiple devices

### ISSUE THREAD

**Issue by anu-vaid** [NicosKaralis/pushmeup#30]
Thanks for the easy to use gem. Can I use pushmeup to send a notification to multiple devices simultaneously? Is there a limit on the number of devices I can notify with one call? Are there any throttling requirements that I should be aware of?

**Comment by NicosKaralis** [comment]
Well, each platform has its own limits.

APNS have no limits, but they strongly recommend that you leave the connection open, they say if you open and close connection too frequently they can revoke your access. If you inspect the `APNS.send_notification` and `APNS.send_notifications` you'll see that we open one connection and try to send as many as possible.

GCM on the other hand you can send at most 1000 pushes with one request, that means you can send for a 1000 different recipients with one request, other than that GCM has no limits. ([source](http://developer.android.com/training/cloudsync/gcm.html#multicast))
