### ISSUE TITLE
GCM mismatchSenderId

### ISSUE THREAD

**Issue by cdownard** [NicosKaralis/pushmeup#43]
I've been reading through doc after doc after doc (and by that I mean site after site) where people run into this error and it has to do with the project # for the app.

``` ruby
target = "reallylongdeviceid" 
GCM.format = :json
GCM.key = "apikey" 
# found at https://console.developers.google.com/project/766********7/apiui/credential?authuser=0
# the number found in the url there, the project number, is a linked sender id on play.google.com/apps/publish/etc....../
data = {:message => "test push" }
GCM.send_notification(target, data) 
GCM.send_notification(target)
```

`Output`:

```
[{:response=>"success", :body=>{"multicast_id"=>obfuscated, "success"=>0, "failure"=>1, "canonical_ids"=>0, "results"=>[{"error"=>"MismatchSenderId"}]}, :headers=>{"content-type"=>["application/json; charset=UTF-8"], "date"=>["Wed, 03 Sep 2014 19:08:56 GMT"], "expires"=>["Wed, 03 Sep 2014 19:08:56 GMT"], "cache-control"=>["private, max-age=0"], "x-content-type-options"=>["nosniff"], "x-frame-options"=>["SAMEORIGIN"], "x-xss-protection"=>["1; mode=block"], "server"=>["GSE"], "alternate-protocol"=>["443:quic"], "connection"=>["close"]}, :status_code=>200}] 
```

```
[{:response=>"success", :body=>{"multicast_id"=>obfuscated, "success"=>0, "failure"=>1, "canonical_ids"=>0, "results"=>[{"error"=>"MismatchSenderId"}]}, :headers=>{"content-type"=>["application/json; charset=UTF-8"], "date"=>["Wed, 03 Sep 2014 19:10:19 GMT"], "expires"=>["Wed, 03 Sep 2014 19:10:19 GMT"], "cache-control"=>["private, max-age=0"], "x-content-type-options"=>["nosniff"], "x-frame-options"=>["SAMEORIGIN"], "x-xss-protection"=>["1; mode=block"], "server"=>["GSE"], "alternate-protocol"=>["443:quic"], "connection"=>["close"]}, :status_code=>200}] 
```

I inherited this project and apparently push notifications never worked. It looks like it's an error with the ID that the app registers with, but what's in the phonegap codebase when the app starts, and what's setup as a linked sender ID match. I'm new to looking at push notifications and just want to try to get this working but I'm not sure where to look. This probably isn't related to pushmeup, but any help someone could offer I would appreciate.

Thanks!

**Comment by amit-m** [comment]
facing the same issue

**Comment by cdownard** [comment]
This turned out to be an issue in being provided the wrong API key for the company's Google account. The company had another API key under a different user.

As soon as I switched the API key and updated the whitelisted IP addresses to be able to send push notifications, everything started working. I apologize for posting this issue here however maybe it will server others.
1. Ensure Google Cloud Messaging for Android is turned on
2. Ensure you have the correct API key
3. Edit the list of IP addresses authorized to send push notifications via GCM for Android and include your dev server ip
4. Ensure the ID that's being attached at your app level is correct. When you view your project on google's dev console, the ID shows up in the URL. That needs to be properly attached and that's the ID devices need to be using to register.
5. Profit.

**Comment by shyam3** [comment]
i am getting this message from server when i register my android device 
{"multicast_id":7751536172966571167,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}

show any one help me for remove this error /bug  successfully and register my android device for gcm registration.

**Comment by mahra2612** [comment]
same issue facing....

**Comment by himangshu-149** [comment]
have you sorted out the problem you were facing? @ mahra2612
