### ISSUE TITLE
iOS 8 not receiving push notifications

### ISSUE THREAD

**Issue by btate** [NicosKaralis/pushmeup#44]
I'm testing this out with a push to both an iOS 7 install and an iOS 8 install.  The iOS 7 notifications are there but not iOS 8.  Has anyone else run into this?

**Comment by jnbt** [comment]
I have no problems sending push notifications to iOS 8 devices, but I only tested it with push tokens generated from iOS 8. Perhaps they changed?

**Comment by btate** [comment]
Im doing the push to my iPhone 6. It's a new phone so it was registered under iOS 8. My buddy's iPhone 5s on iOS 7 gets the pushes but I don't.

**Comment by jnbt** [comment]
Perhaps it's a problem in the app? The code for getting a push token has changed for iOS8 as `registerForRemoteNotificationTypes` is deprecated: 
https://developer.apple.com/library/ios/documentation/uikit/reference/UIApplication_Class/index.html#//apple_ref/occ/instm/UIApplication/registerForRemoteNotificationTypes:

We had troubles with this change and didn't received any push tokens on iOS8 before changing the code. Have you tried using the device token using another push tool? (e.g. https://github.com/noodlewerk/NWPusher)

**Comment by btate** [comment]
I'm using the iOS 8 registration code.  I have a device token registered on my server. 

## 

Thanks,
Brandon

**Comment by btate** [comment]
I just tested it with the pusher app and I get the push notifications.  The problem is specific to when I send it out with the pushmeup gem.   

## 

Thanks,
Brandon

**Comment by btate** [comment]
Got it figured out.  When I tested this on iOS 8 originally the phone was plugged in so it was in debug mode.  So I got a device token for the sandbox.  My server is using production apns because my test builds go out ad hoc.  So the production apns couldn't push to the sandbox device id.  

Sorry about that.  At least it was something simple.

## 

Thanks,
Brandon

**Comment by d4rky-pl** [comment]
I believe this issue may now be closed..?

**Comment by jnbt** [comment]
+1
