### ISSUE TITLE
GCM collapse_key (send-to-sync) not worked as expected

### ISSUE THREAD

**Issue by ethagnawl** [NicosKaralis/pushmeup#62]
My understanding is that specifying a collapse_key (e.g. a chat room ID) will prevent duplicate notifications concerning that chat room from stacking up. If this is the intended behavior, this feature is not working. 

Here's my implementation:

`GCM.send_notification token, {alert: 'collapse_key test'}, {collapse_key: 'something_unique', time_to_live: 3600}`

And the result:

![screenshot_2015-03-09-11-21-13](https://cloud.githubusercontent.com/assets/289949/6557878/e0ba87dc-c64e-11e4-9a3a-8ba4037bad77.png)

**Comment by rajohns08** [comment]
That is not how `collapse_key` works. It doesn't prevent notifications from stacking on the client device, it prevents the notifications from stacking on Google's GCM servers. So if you send notificationA and it goes all the way to the client device before notificationB is sent, when notificationB goes through, it will (and should) stack in the device's notification tray. If you send notificationA and before notificationA leaves the GCM servers, notificationB comes in with same `collapse_key` and registration id, notificationA will be discarded and never sent from GCM servers to client device.
