### ISSUE TITLE
should the configuration be placed as a file in the initializers file?

### ISSUE THREAD

**Issue by dgaeta** [NicosKaralis/pushmeup#7]
This is not an issue just a question:

should the configuration be placed as a file in the initializers file or included in the files that will be sending the push?

**Comment by NicosKaralis** [comment]
Yes, the config needs to be set only once, an initializer is the best place to put the config

**Comment by DrBeak1** [comment]
Hey dannythejedi, sorry to crash this thread -- can you tell me where you ended up placing the configuration variables? I asked in this thread: https://github.com/NicosKaralis/pushmeup/issues/19 but haven't gotten any attention. I'm somewhat new to rails so need a bit more hand-holding than usual.

If you have time, I would greatly appreciate a response. -- thank you!
